### ISSUE TITLE
Allow setting plain (non-tls) and insecure (not certificate checking) per policy host

### ISSUE THREAD

**Issue by ereslibre** [chimera-kube/policy-server#23]
It is now possible to configure a number of policies [reading the `policies.yml` file](https://github.com/chimera-kube/policy-server/issues/5).

There are several options where a policy module can come from nowadays:

* `file`: not interesting for this case.
* `http`: not interesting for this case.
* `https`
* `registry`

A couple of scenarios:

1) The `https` case by default will check that the presented server certificate is valid, but it should be possible to override this check for some hosts if the user desires so.

2) The `registry` could potentially point to either a non-tls or a tls registry, since the schema offers no differentiation as `http`/`https` do.

Adding a `sources.yml` file that can be provided as an argument to the `policy-server` is desirable. The `sources.yml` file will be composed of a top level map with two optional entries:

* `insecure_sources`: is an array of `host:port` similar to the [Docker's insecure registries behavior](https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry). In this case, the `policy-server` will first try to download the artifact using https with no certificate validation, and if that connection fails, it will use plain http.

* `sources_authorities`: is a map of `host:port` as keys, and an object containing `ca-path` that points to the pem encoded CA certificate or chain (if subordinate).

Example:

```yaml
insecure_sources: ["my-registry.local.lan", "other-registry.local.lan:5001"]
sources_authorities:
  "self-signed.svc.lan:5001":
    ca-path: "/foo/bar.pem"
  other-self-signed.svc.lan:
    ca-path: "/foo/bar.pem"
```

When using the `registry://` scheme as the origin for a Wasm module, if the `host` or `host:port` is not present in either `insecure_sources` or `sources_authorities`, then the connection will be always TLS with certificate verification using the system CA certificates -- if this connection fails, the connection won't be retried over non-tls.
