### ISSUE TITLE
Add common attributes to policies

### ISSUE THREAD

**Issue by flavio** [chimera-kube/policy-server#27]
Many policies have to implement concepts like `allowed_users` and `allowed_groups` inside of their code. We should instead move these attributes, and their handling, inside of the Policy Server. By doing that we will DRY policies and save quite some time to policy authors.

The idea is to introduce these shared attributes that can be enabled on each policy:
  * `allowed_users`: list of users who are not affected by the policy
  * `allowed_groups` list of groups who are not affected by the policy
  * `target_users`: reduce the scope of the policy only to requests made by these users
  * `target_groups`: reduce the scope of the policy only to requests made by users who belong to these groups

Each one of these fields would be optional.

This is how the policies would behave, given the following scenarios:
  * Both`allowed_` attributes are not set: the policy will evaluate all requests, regardless of the author
  * Both `target_` attributes are not set: the policy will evaluate all requests, regardless of the author
  * `allowed_` and `target_` are set at the same time: only requests originated from `target_` are going to be evaluated by the policy. If a request is coming from an `allowed_user` or `allowed_groups` the request will be immediately approved.

## Examples

Apply the policy to all the users of the clusters except for `alice` and all the users who belong to the `administrators` group:

```yaml
privileged_pods:
  url: registry://ghcr.io/chimera-kube/policies/psp-apparmor:v0.1.0
  settings:
    allowed_profiles:
    - runtime/default
    - localhost/my-special-workload
  allowed_users:
  - alice
  allowed_groups:
  - administrators
```

Apply the policy only to the requests coming from the user `bob` and all the users who belong to the group `tenant-a`:

```yaml
privileged_pods:
  url: registry://ghcr.io/chimera-kube/policies/psp-apparmor:v0.1.0
  settings:
    allowed_profiles:
    - runtime/default
    - localhost/my-special-workload
  target_users:
  - bob
  target_groups:
  - tenant-a
```

Apply the policy only to the requests made by users who belong to the `mortals` group. At the same time exempt the user `bob` from this policy:

```yaml
privileged_pods:
  url: registry://ghcr.io/chimera-kube/policies/psp-apparmor:v0.1.0
  settings:
    allowed_profiles:
    - runtime/default
    - localhost/my-special-workload
  allowed_users:
  - bob
  target_groups:
  - mortals
```

Let's assume user `bob` belongs to the `mortals` group. With the configuration shown above the requests coming from user `bob` would not be processed by the policy.
