### ISSUE TITLE
Read policy settings from configuration file

### ISSUE THREAD

**Issue by flavio** [chimera-kube/policy-server#5]
Read the list of policies to host from a configuration file.

The structure of the configuration file should look like that:

```yaml
policies:
  - endpoint: "/toleration1"
    url: registry://ghcr.io/chimera-kube/toleration-policy:1.0.0
    settings:
      taint-key: dedicated
      taint-value: tenantA
      allowed_groups:
      - administrators
      - tenant-a-users
  - endpoint: "/toleration2"
    url: registry://ghcr.io/chimera-kube/toleration-policy:1.0.0
    settings:
      taint-key: dedicated
      taint-value: tenantB
      allowed_groups:
      - administrators
      - tenant-b-users
  - endpoint: "/toleration2"
    url: registry://ghcr.io/chimera-kube/pod-privileged:1.0.0
    settings:
      trusted_users:
      - flavio
      trusted_groups:
      - admins
``` 

This allows the same policy to be instantiated multiple times, under different endpoints, with different flags.
